stages:
  - build

osx_job:
  stage: build
  tags:
    - osx
  script:
    - apt-get update && apt-get install -y python-dev build-essential
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python get-pip.py
    - pip install awscli
    - yarn
    - yarn package && aws s3 sync release/*.dmg s3://walletcs-app-builds/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

  only:
    - master
